### PR TITLE
Translated to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by Lucas559-noob**
I think it don't have errors in game
and is my first pull request, probably I'm doing something wrong

### CODE REVIEW

**Comment by zymex22** [comment]
Seems good thank you @Lucas559-noob it will be uploaded on next steam update =)

**Review by zymex22 — APPROVED** [review]

**Comment by lilwhitemouse** [comment]
Oh hey, just noticed this - are there any objections to merging this?

**Comment by Lucas559-noob** [comment]
> Oh hey, just noticed this - are there any objections to merging this?

No? Idk I never saw this word "objections" in my life, and the translation too, so idk what it means

**Comment by lilwhitemouse** [comment]
@Lucas559-noob The question was directed @zymex22 (@zymex) - I want to double check with them before pulling it into the master branch, but also wanted to make sure we didn't forget about it. :)  This should remind them the PR exists!

**Pull request merged**
