### PR TITLE
#335 added Info to the Description of the Building

### LINKED ISSUE #335: (Request) Add Resource Info to the Help Tab for all random drills
The Idea is to display the following information in the Help tab of all Dynamic/Random Drills:
_(All Drills with a random element)_

- Items they can Drill / get by random
- (Maybe) Chance of the Item

### PR DESCRIPTION
**Pull request by Sn1p3rr3c0n**
resolves #335 

image

@zymex22 is `Weight` understandable for a user or should we present it differently? if so suggestions?

otherwise ready to merge

### CODE REVIEW

**Comment by zymex22** [comment]
@Sn1p3rr3c0n i never really understood weight system xD to me % or somethin 1 out of 100 or something feel more natural to me, to use and understand.

might need to be something else but, again im still not fully understand weight system when someone on chat tried teach me? might even been thorny that tried xD

i would say its upto @lilwhitemouse or someone to determine what a good alternative could be? =)

**Comment by lilwhitemouse** [comment]
I will see what I can do :)

I seem to recall the code was particularly dense, but that may just be my memory!

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 it should be ready for merge now

**Comment by zymex22** [comment]
image

**Comment by zymex22** [comment]
anyways i have tested it, and looks really awesome and pro, so if you can resolve conflict @Sn1p3rr3c0n you can just merge it =) good job! :D

**Pull request merged**
