### PR TITLE
Fixed Power use on Load

### LINKED ISSUE #120: power use on "assemblers"
**Comment from Malkav in steam comments:**
I've found a glitch with the Metal Refinery. When I first load a save, it shows a power consumption of 0W. Once selected and the power tab opened, it changes to the correct amount and works properly. While it is at 0W, it runs at normal speed even though it's using no power.

Is this a new bug after Fueled was applied to assemblers? (metal refinery is using assembler thingclalss)

### PR DESCRIPTION
**Pull request by Sn1p3rr3c0n**
resolves #120 

Note:
I am not sure why we need to call it in this way. My current assumption is that is related to the loading progress and executes it at the correct time.
`this.MapManager.NextAction(somecall);`
`this.MapManager.AfterAction(5, somecall);`

### CODE REVIEW

**Comment by lilwhitemouse** [comment]
I'm pretty sure there is already a `SetPower()` method somewhere.

**Comment by lilwhitemouse** [comment]
It's probably better to change CompPowerWorkSetter's `protected SetPower()` to a `public UpdatePower()` (or `PowerUpdated()` or `RefreshPower()` or ...?)

Then one can call
```
this.GetComp<CompPowerWorkSetting>()?.UpdatePower();
```
instead of calculating directly, which may be inappropriate if CompPowerWorkSetting every changes.

**Comment by lilwhitemouse** [comment]
It's probably also worth adding an `UpdatePower()` (`RefreshPower()`, whatever) to the `IPowerSupplyMachine` interface, and then calling
```
this.RangePowerSupplyMachine?.UpdatePowerUsage();
```
Also, maybe "UpdatePowerUsage()"?

**Comment by lilwhitemouse** [comment]
Long term, I would prefer to see the CompPowerWorkSetting replaced with a new ThingComp derived from CompPowerTrader, that would handle the changes to power consumption directly.  Going through an interface now means less likelihood of breaking anything later.

**Comment by zymex22** [comment]
so status short term?

**Comment by lilwhitemouse** [comment]
Update the interface to include `RefreshPowerStatus()`

**Comment by lilwhitemouse** [comment]
My brain is tired enough I can't think of the appropriate name right now :laughing:

**Pull request merged**
