### PR TITLE
Update SimpleFridge.xml

### PR DESCRIPTION
**Pull request by feeddanoob**
Current Desc included rim fridge instead of simple util fridge for the simple util patch. This makes it consistent.

### CODE REVIEW

**Comment by Sn1p3rr3c0n** [comment]
I fully agree with the concept (it uses Simple Fridge it should reference it)
In any case this is better then how it was before.
However I'm undecided on how that Sentence flows.

@InsanityPrelude What do you think?

**Comment by InsanityPrelude** [comment]
"Simple Utilities: Fridge" doesn't really sound like a brand, but RimFridge does, so I agree that a 1:1 drop-in replacement doesn't seem like it fits.

There's not really a short and pithy description of it, unless you want to just swap in SUFridge or SU-Fridge or something like that.  Or maybe you could just say "Owlchemist branded?"  Here's my best shot:

"Compatible with Simple Utilities: Fridge, this is a refrigerated version of the Digital Storage Unit that stores up to 512 stacks of food. It consumes 10 W of power per stack of items. During a power outage, items already inside will be safe, but the DSU will not be able to store more."

**Comment by feeddanoob** [comment]
What if you just truncate it, 
"A S.U:F branded, refrigerated version of the Digital Storage Unit that stores up to 512 stacks of food. Consumes 10 W of power per stack of items. In the event of a power outage, items already inside will be safe, but the DSU will not be able to store more."

**Comment by Sn1p3rr3c0n** [comment]
@feeddanoob If you update it to any of the options discussed on discord we can merge this

**Pull request merged**
