### PR TITLE
Issue123

### LINKED ISSUE #123: Assembler mute masterwork
Assemblers have a tendency to throw a masterwork created notification even when its not even making a masterwork.

Solution?
mute notification and just let it create random quality as it wants, so it dont confuse ppl
OR
Fix it so it so it throw notification at right times and not just randomly

its from this comment and many other:

> i get a message saying "machine produced a masterwork anorak" but when i see said anorak it can be every quality, can be master or can be normal or horrible, etc, i use vanilla leathers and the other mods i have dont change anything of clothes

> There does seem to be something weird going on with the products it does make, however. Very often I get the alert that it has produced a masterwork item (clothing, weapons, even art), but it seems like what the assembler produces (and triggers the masterwork notification) and what it actually outputs are very different quality levels. This continues to occur even after the assembler gets a pretty high speed boost to crafting a certain product. By the way; thanks for updating and continuing work on this mod, I have thoroughly enjoyed it even if I'm getting a little confused about the assemblers.

### PR DESCRIPTION
**Pull request by Sn1p3rr3c0n**
resolves #123 

@lilwhitemouse some points from my side:

- I would have preferred to patch `public static QualityCategory GenerateQualityCreatedByPawn(Pawn pawn, SkillDef relevantSkill)` but and call `public QualityCategory GetRandomProductionQuality()` from there but i dont know how to get the correct instance of `Building_Assembler_Learning` for the calculation
- probably should move the patch to another file any suggestions?

### CODE REVIEW

**Comment by Sn1p3rr3c0n** [comment]
@lilwhitemouse just noticed working on a different issue that we have a Harmony patch folder. I will move it there later.

**Comment by lilwhitemouse** [comment]
@zymex22 If you can build this, it's safe to merge :)

**Review by lilwhitemouse — APPROVED** [review]

**Comment by zymex22** [comment]
@lilwhitemouse 
i cannot =) 
image

**Comment by zymex22** [comment]
image

**Comment by lilwhitemouse** [comment]
Okay, then.  I'll use the correct syntax for C#, shall I?

Thanks for building - I'm not in a place I can do that easily.  Or check syntax.

**Comment by zymex22** [comment]
image
well done :D works now =)

doing 3d printer build and running back an fowards looking up info =) there you go

**Comment by zymex22** [comment]
@lilwhitemouse

**Pull request merged**
