### PR TITLE
support mod SaveStorageSetting

### PR DESCRIPTION
**Pull request by RenYueHD**
I find a mod SaveStorageSetting ,it can export the storage setting and use in another save,but this mod dont support it.
so i fork and recode it
see [[KV] Save Storage, Outfit, Crafting, Drug & Operation Settings [ModSync]](https://ludeon.com/forums/index.php?topic=34075.0)  and  [Add Support for Save Storage Settings](https://ludeon.com/forums/index.php?topic=34100.msg347977)
i tested it and it can work with the storages of this mod

### CODE REVIEW

**Comment by lilwhitemouse** [comment]
Rather than add a 3rd party dependency, we would prefer KV move to a Harmony patch for all storage buildings. It it turns out that isn't an option, we'll consider adding a way to do this.

Would this other mod work for you? It seems to do the same things, without requiring other mods doing things.
https://steamcommunity.com/sharedfiles/filedetails/?id=1467209473&searchtext=export

**Comment by RenYueHD** [comment]
> Rather than add a 3rd party dependency, we would prefer KV move to a Harmony patch for all storage buildings. It it turns out that isn't an option, we'll consider adding a way to do this.
> 
> Would this other mod work for you? It seems to do the same things, without requiring other mods doing things.
> https://steamcommunity.com/sharedfiles/filedetails/?id=1467209473&searchtext=export

thanks ,i am using the Export Agency ,but its too difficult to use and does not support Automatic picker
but I also think that third-party mod should not be integrated in this mod
maybe we i need to rewrite the Export Agency ?

**Comment by KiameV** [comment]
Just a heads up, Save Storage, Outfit, Crafting & Drug settings now supports all types of Building_Storage. Anyone using that mod please update to the latest version and see if it works.

-KV

**Comment by KiameV** [comment]
I was informed that some of the buildings are not of Building_Storage. I do have a utility that can be added to as a dll along with any mod to add support for any Building type - https://github.com/KiameV/rimworld-SaveStorageSettings/releases/tag/util

**Comment by zymex22** [comment]
@lilwhitemouse @Sn1p3rr3c0n may be able so answer that?

**Pull request closed without merging**
